# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created: Sun Apr  3 16:50:44 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(687, 562)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.main_stacked_widget = QtGui.QStackedWidget(self.centralwidget)
        self.main_stacked_widget.setObjectName(_fromUtf8("main_stacked_widget"))
        self.main_page = QtGui.QWidget()
        self.main_page.setMinimumSize(QtCore.QSize(669, 544))
        self.main_page.setObjectName(_fromUtf8("main_page"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.main_page)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.led_filter = QtGui.QLineEdit(self.main_page)
        self.led_filter.setObjectName(_fromUtf8("led_filter"))
        self.verticalLayout_3.addWidget(self.led_filter)
        self.led_list_view = QtGui.QListView(self.main_page)
        self.led_list_view.setIconSize(QtCore.QSize(0, 0))
        self.led_list_view.setGridSize(QtCore.QSize(0, 0))
        self.led_list_view.setObjectName(_fromUtf8("led_list_view"))
        self.verticalLayout_3.addWidget(self.led_list_view)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.add_led_button = QtGui.QToolButton(self.main_page)
        self.add_led_button.setMinimumSize(QtCore.QSize(32, 32))
        self.add_led_button.setAutoRaise(False)
        self.add_led_button.setObjectName(_fromUtf8("add_led_button"))
        self.horizontalLayout_5.addWidget(self.add_led_button)
        self.remove_led_button = QtGui.QToolButton(self.main_page)
        self.remove_led_button.setMinimumSize(QtCore.QSize(32, 32))
        self.remove_led_button.setAutoRaise(False)
        self.remove_led_button.setObjectName(_fromUtf8("remove_led_button"))
        self.horizontalLayout_5.addWidget(self.remove_led_button)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(14, -1, -1, -1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.voltage_label = QtGui.QLabel(self.main_page)
        self.voltage_label.setMinimumSize(QtCore.QSize(0, 0))
        self.voltage_label.setObjectName(_fromUtf8("voltage_label"))
        self.gridLayout.addWidget(self.voltage_label, 6, 1, 1, 1)
        self.label = QtGui.QLabel(self.main_page)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.current_spinbox = QtGui.QDoubleSpinBox(self.main_page)
        self.current_spinbox.setMaximum(9999999.0)
        self.current_spinbox.setObjectName(_fromUtf8("current_spinbox"))
        self.gridLayout.addWidget(self.current_spinbox, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.main_page)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.main_page)
        self.label_10.setMinimumSize(QtCore.QSize(0, 30))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.input_power_label = QtGui.QLabel(self.main_page)
        self.input_power_label.setObjectName(_fromUtf8("input_power_label"))
        self.gridLayout.addWidget(self.input_power_label, 8, 1, 1, 1)
        self.voltage_group_combobox = QtGui.QComboBox(self.main_page)
        self.voltage_group_combobox.setMinimumSize(QtCore.QSize(0, 0))
        self.voltage_group_combobox.setObjectName(_fromUtf8("voltage_group_combobox"))
        self.gridLayout.addWidget(self.voltage_group_combobox, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.main_page)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.thermal_power_label = QtGui.QLabel(self.main_page)
        self.thermal_power_label.setObjectName(_fromUtf8("thermal_power_label"))
        self.gridLayout.addWidget(self.thermal_power_label, 10, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.main_page)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.main_page)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.radiant_flux_label = QtGui.QLabel(self.main_page)
        self.radiant_flux_label.setObjectName(_fromUtf8("radiant_flux_label"))
        self.gridLayout.addWidget(self.radiant_flux_label, 9, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.led_header_label = QtGui.QLabel(self.main_page)
        self.led_header_label.setMinimumSize(QtCore.QSize(0, 32))
        self.led_header_label.setObjectName(_fromUtf8("led_header_label"))
        self.horizontalLayout_6.addWidget(self.led_header_label)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.edit_led_button = QtGui.QPushButton(self.main_page)
        self.edit_led_button.setMaximumSize(QtCore.QSize(75, 16777215))
        self.edit_led_button.setFlat(False)
        self.edit_led_button.setObjectName(_fromUtf8("edit_led_button"))
        self.horizontalLayout_6.addWidget(self.edit_led_button)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        self.label_2 = QtGui.QLabel(self.main_page)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.luminous_flux_label = QtGui.QLabel(self.main_page)
        self.luminous_flux_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.luminous_flux_label.setObjectName(_fromUtf8("luminous_flux_label"))
        self.gridLayout.addWidget(self.luminous_flux_label, 7, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 0, 1, 1)
        self.brightness_group_combobox = QtGui.QComboBox(self.main_page)
        self.brightness_group_combobox.setObjectName(_fromUtf8("brightness_group_combobox"))
        self.gridLayout.addWidget(self.brightness_group_combobox, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.main_page)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.main_page)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.temperature_spinbox = QtGui.QDoubleSpinBox(self.main_page)
        self.temperature_spinbox.setMaximum(9999999.0)
        self.temperature_spinbox.setObjectName(_fromUtf8("temperature_spinbox"))
        self.gridLayout.addWidget(self.temperature_spinbox, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.main_page)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.radiant_efficiency_label = QtGui.QLabel(self.main_page)
        self.radiant_efficiency_label.setObjectName(_fromUtf8("radiant_efficiency_label"))
        self.gridLayout.addWidget(self.radiant_efficiency_label, 11, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_2.setStretch(1, 1)
        self.main_stacked_widget.addWidget(self.main_page)
        self.editor_page = QtGui.QWidget()
        self.editor_page.setObjectName(_fromUtf8("editor_page"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.editor_page)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(20)
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.led_editor_navigator_list = QtGui.QListWidget(self.editor_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.led_editor_navigator_list.sizePolicy().hasHeightForWidth())
        self.led_editor_navigator_list.setSizePolicy(sizePolicy)
        self.led_editor_navigator_list.setMinimumSize(QtCore.QSize(0, 0))
        self.led_editor_navigator_list.setObjectName(_fromUtf8("led_editor_navigator_list"))
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.led_editor_navigator_list.addItem(item)
        self.horizontalLayout_4.addWidget(self.led_editor_navigator_list)
        self.editor_stacked_widget = QtGui.QStackedWidget(self.editor_page)
        self.editor_stacked_widget.setObjectName(_fromUtf8("editor_stacked_widget"))
        self.parameter_page = QtGui.QWidget()
        self.parameter_page.setObjectName(_fromUtf8("parameter_page"))
        self.gridLayout_3 = QtGui.QGridLayout(self.parameter_page)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.manufacturer_combo = QtGui.QComboBox(self.parameter_page)
        self.manufacturer_combo.setEditable(True)
        self.manufacturer_combo.setObjectName(_fromUtf8("manufacturer_combo"))
        self.manufacturer_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.manufacturer_combo, 1, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 7, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.parameter_page)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.parameter_page)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.parameter_page)
        self.label_19.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.parameter_page)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
        self.name_edit = QtGui.QLineEdit(self.parameter_page)
        self.name_edit.setObjectName(_fromUtf8("name_edit"))
        self.gridLayout_3.addWidget(self.name_edit, 0, 2, 1, 1)
        self.label_22 = QtGui.QLabel(self.parameter_page)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 5, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.parameter_page)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 6, 0, 1, 1)
        self.thermal_resistance_spin = QtGui.QDoubleSpinBox(self.parameter_page)
        self.thermal_resistance_spin.setMaximum(9999999.0)
        self.thermal_resistance_spin.setObjectName(_fromUtf8("thermal_resistance_spin"))
        self.gridLayout_3.addWidget(self.thermal_resistance_spin, 5, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.parameter_page)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_3.addWidget(self.label_17, 0, 0, 1, 1)
        self.reference_temperature_spin = QtGui.QDoubleSpinBox(self.parameter_page)
        self.reference_temperature_spin.setMaximum(9999999.0)
        self.reference_temperature_spin.setObjectName(_fromUtf8("reference_temperature_spin"))
        self.gridLayout_3.addWidget(self.reference_temperature_spin, 6, 2, 1, 1)
        self.typical_current_spin = QtGui.QDoubleSpinBox(self.parameter_page)
        self.typical_current_spin.setMaximum(9999999.0)
        self.typical_current_spin.setObjectName(_fromUtf8("typical_current_spin"))
        self.gridLayout_3.addWidget(self.typical_current_spin, 4, 2, 1, 1)
        self.typical_voltage_spin = QtGui.QDoubleSpinBox(self.parameter_page)
        self.typical_voltage_spin.setMaximum(9999999.0)
        self.typical_voltage_spin.setObjectName(_fromUtf8("typical_voltage_spin"))
        self.gridLayout_3.addWidget(self.typical_voltage_spin, 3, 2, 1, 1)
        self.family_combo = QtGui.QComboBox(self.parameter_page)
        self.family_combo.setEditable(True)
        self.family_combo.setObjectName(_fromUtf8("family_combo"))
        self.family_combo.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.family_combo, 2, 2, 1, 1)
        self.editor_stacked_widget.addWidget(self.parameter_page)
        self.brightness_group_page = QtGui.QWidget()
        self.brightness_group_page.setObjectName(_fromUtf8("brightness_group_page"))
        self.verticalLayout = QtGui.QVBoxLayout(self.brightness_group_page)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.brightness_group_table_view = QtGui.QTableView(self.brightness_group_page)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightness_group_table_view.sizePolicy().hasHeightForWidth())
        self.brightness_group_table_view.setSizePolicy(sizePolicy)
        self.brightness_group_table_view.setObjectName(_fromUtf8("brightness_group_table_view"))
        self.verticalLayout.addWidget(self.brightness_group_table_view)
        self.editor_stacked_widget.addWidget(self.brightness_group_page)
        self.voltage_group_page = QtGui.QWidget()
        self.voltage_group_page.setObjectName(_fromUtf8("voltage_group_page"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.voltage_group_page)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.voltage_group_table_view = QtGui.QTableView(self.voltage_group_page)
        self.voltage_group_table_view.setObjectName(_fromUtf8("voltage_group_table_view"))
        self.voltage_group_table_view.verticalHeader().setCascadingSectionResizes(True)
        self.voltage_group_table_view.verticalHeader().setDefaultSectionSize(0)
        self.horizontalLayout_3.addWidget(self.voltage_group_table_view)
        self.editor_stacked_widget.addWidget(self.voltage_group_page)
        self.current_emission_page = QtGui.QWidget()
        self.current_emission_page.setObjectName(_fromUtf8("current_emission_page"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.current_emission_page)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.current_emission_table_view = QtGui.QTableView(self.current_emission_page)
        self.current_emission_table_view.setObjectName(_fromUtf8("current_emission_table_view"))
        self.verticalLayout_5.addWidget(self.current_emission_table_view)
        self.editor_stacked_widget.addWidget(self.current_emission_page)
        self.current_voltage_page = QtGui.QWidget()
        self.current_voltage_page.setObjectName(_fromUtf8("current_voltage_page"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.current_voltage_page)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.current_voltage_table_view = QtGui.QTableView(self.current_voltage_page)
        self.current_voltage_table_view.setObjectName(_fromUtf8("current_voltage_table_view"))
        self.verticalLayout_6.addWidget(self.current_voltage_table_view)
        self.editor_stacked_widget.addWidget(self.current_voltage_page)
        self.temperature_emission_page = QtGui.QWidget()
        self.temperature_emission_page.setObjectName(_fromUtf8("temperature_emission_page"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.temperature_emission_page)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.temperature_emission_table_view = QtGui.QTableView(self.temperature_emission_page)
        self.temperature_emission_table_view.setObjectName(_fromUtf8("temperature_emission_table_view"))
        self.horizontalLayout_7.addWidget(self.temperature_emission_table_view)
        self.editor_stacked_widget.addWidget(self.temperature_emission_page)
        self.temperature_voltage_page = QtGui.QWidget()
        self.temperature_voltage_page.setObjectName(_fromUtf8("temperature_voltage_page"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.temperature_voltage_page)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.temperature_voltage_table_view = QtGui.QTableView(self.temperature_voltage_page)
        self.temperature_voltage_table_view.setObjectName(_fromUtf8("temperature_voltage_table_view"))
        self.horizontalLayout_8.addWidget(self.temperature_voltage_table_view)
        self.editor_stacked_widget.addWidget(self.temperature_voltage_page)
        self.horizontalLayout_4.addWidget(self.editor_stacked_widget)
        self.horizontalLayout_4.setStretch(1, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtGui.QDialogButtonBox(self.editor_page)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.main_stacked_widget.addWidget(self.editor_page)
        self.horizontalLayout.addWidget(self.main_stacked_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.voltage_label.setBuddy(self.voltage_label)

        self.retranslateUi(MainWindow)
        self.main_stacked_widget.setCurrentIndex(0)
        self.editor_stacked_widget.setCurrentIndex(0)
        QtCore.QObject.connect(self.led_editor_navigator_list, QtCore.SIGNAL(_fromUtf8("currentRowChanged(int)")), self.editor_stacked_widget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.name_edit, self.manufacturer_combo)
        MainWindow.setTabOrder(self.manufacturer_combo, self.family_combo)
        MainWindow.setTabOrder(self.family_combo, self.typical_voltage_spin)
        MainWindow.setTabOrder(self.typical_voltage_spin, self.typical_current_spin)
        MainWindow.setTabOrder(self.typical_current_spin, self.thermal_resistance_spin)
        MainWindow.setTabOrder(self.thermal_resistance_spin, self.reference_temperature_spin)
        MainWindow.setTabOrder(self.reference_temperature_spin, self.buttonBox)
        MainWindow.setTabOrder(self.buttonBox, self.led_editor_navigator_list)
        MainWindow.setTabOrder(self.led_editor_navigator_list, self.brightness_group_combobox)
        MainWindow.setTabOrder(self.brightness_group_combobox, self.voltage_group_combobox)
        MainWindow.setTabOrder(self.voltage_group_combobox, self.edit_led_button)
        MainWindow.setTabOrder(self.edit_led_button, self.led_filter)
        MainWindow.setTabOrder(self.led_filter, self.led_list_view)
        MainWindow.setTabOrder(self.led_list_view, self.add_led_button)
        MainWindow.setTabOrder(self.add_led_button, self.remove_led_button)
        MainWindow.setTabOrder(self.remove_led_button, self.temperature_spinbox)
        MainWindow.setTabOrder(self.temperature_spinbox, self.current_spinbox)
        MainWindow.setTabOrder(self.current_spinbox, self.brightness_group_table_view)
        MainWindow.setTabOrder(self.brightness_group_table_view, self.voltage_group_table_view)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LED Tool", None))
        self.led_filter.setPlaceholderText(_translate("MainWindow", "Filter", None))
        self.add_led_button.setText(_translate("MainWindow", "+", None))
        self.remove_led_button.setText(_translate("MainWindow", "−", None))
        self.voltage_label.setText(_translate("MainWindow", "--- V", None))
        self.label.setText(_translate("MainWindow", "Current:", None))
        self.current_spinbox.setSuffix(_translate("MainWindow", " mA", None))
        self.label_8.setText(_translate("MainWindow", "Input Power:", None))
        self.label_10.setText(_translate("MainWindow", "Radiant Efficiency:", None))
        self.input_power_label.setText(_translate("MainWindow", "--- W", None))
        self.label_9.setText(_translate("MainWindow", "Thermal Power:", None))
        self.thermal_power_label.setText(_translate("MainWindow", "--- W", None))
        self.label_5.setText(_translate("MainWindow", "Luminous Flux:", None))
        self.label_4.setText(_translate("MainWindow", "Voltage Group:", None))
        self.radiant_flux_label.setText(_translate("MainWindow", "--- W", None))
        self.led_header_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">LUMILEDS LUXEON F ES</span></p></body></html>", None))
        self.edit_led_button.setText(_translate("MainWindow", "Edit", None))
        self.label_2.setText(_translate("MainWindow", "Temperature:", None))
        self.luminous_flux_label.setText(_translate("MainWindow", "--- lm", None))
        self.label_7.setText(_translate("MainWindow", "Radiant Flux:", None))
        self.label_3.setText(_translate("MainWindow", "Brightness Group:", None))
        self.temperature_spinbox.setSuffix(_translate("MainWindow", " °C", None))
        self.label_6.setText(_translate("MainWindow", "Voltage:", None))
        self.radiant_efficiency_label.setText(_translate("MainWindow", "--- %", None))
        __sortingEnabled = self.led_editor_navigator_list.isSortingEnabled()
        self.led_editor_navigator_list.setSortingEnabled(False)
        item = self.led_editor_navigator_list.item(0)
        item.setText(_translate("MainWindow", "Parameter", None))
        item = self.led_editor_navigator_list.item(1)
        item.setText(_translate("MainWindow", "Brightness Groups", None))
        item = self.led_editor_navigator_list.item(2)
        item.setText(_translate("MainWindow", "Voltage Groups", None))
        item = self.led_editor_navigator_list.item(3)
        item.setText(_translate("MainWindow", "Current vs. Emission", None))
        item = self.led_editor_navigator_list.item(4)
        item.setText(_translate("MainWindow", "Current vs. Voltage", None))
        item = self.led_editor_navigator_list.item(5)
        item.setText(_translate("MainWindow", "Temperature vs. Emission", None))
        item = self.led_editor_navigator_list.item(6)
        item.setText(_translate("MainWindow", "Temperature vs. Voltage", None))
        self.led_editor_navigator_list.setSortingEnabled(__sortingEnabled)
        self.manufacturer_combo.setItemText(0, _translate("MainWindow", "OSRAM", None))
        self.label_20.setText(_translate("MainWindow", "Typical Voltage:", None))
        self.label_18.setText(_translate("MainWindow", "Manufacturer:", None))
        self.label_19.setText(_translate("MainWindow", "Family:", None))
        self.label_21.setText(_translate("MainWindow", "Typical Current:", None))
        self.name_edit.setText(_translate("MainWindow", "LA T67F", None))
        self.label_22.setText(_translate("MainWindow", "Thermal Resistance:", None))
        self.label_23.setText(_translate("MainWindow", "Reference Temperature:", None))
        self.thermal_resistance_spin.setSuffix(_translate("MainWindow", " K/W", None))
        self.label_17.setText(_translate("MainWindow", "Name:", None))
        self.reference_temperature_spin.setSuffix(_translate("MainWindow", " °C", None))
        self.typical_current_spin.setSuffix(_translate("MainWindow", " mA", None))
        self.typical_voltage_spin.setSuffix(_translate("MainWindow", " V", None))
        self.family_combo.setItemText(0, _translate("MainWindow", "TOPLED", None))

